### PR TITLE
Migrate ca.crt to ca-bundle.crt

### PR DESCRIPTION
**Pull request by sdodson**

### CODE REVIEW

**Comment by sdodson** [comment]
@abutcher PTAL works around recent changes to ca.crt in upgrades

**Comment by dgoodwin** [comment]
Is this safe to run for a 3.1 -> 3.2, or 3.2 -> 3.3 upgrade? In this location it'll still trigger for all I think, though I suppose we have agreed that master = 3.3 by this point, however I still use this code to install and upgrade 3.1+ routinely. 

Would it be good to do another hook like these: https://github.com/openshift/openshift-ansible/pull/2211/files#diff-b9082edc92129fbb30c8bd271e23fd1eR65

**Comment by sdodson** [comment]
I think this should be done anywhere that the current code in master makes it to, there are other tasks that rely on that path being there. Meaning, if we merge master into enterprise-3.2 we'll want it there too. Maybe I should also do it in the config playbook? If they were to re-run the config playbook now it would fail because the restart master task looks for ca-bundle.crt that wouldn't exist. Lets see what @abutcher thinks.

**Comment by dgoodwin** [comment]
But if I used master, and installed 3.2 (assuming we don't merge it back), would I get a failure?

**Comment by sdodson** [comment]
Updated to add failed_when: false, added the same steps to config playbook too. Testing to see what happens on a clean install, suspect it should be fine.

**Comment by abutcher** [comment]
ca-bundle.crt will be created during 3.2 installs so this is mainly for the 3.1->3.2 upgrade. I think we may want to reverse the checking logic and only link when ca-bundle.crt doesn't exist while upgrading since it may contain multiple CA's.

**Comment by sdodson** [comment]
Updated to only migrate when ca.crt is a normal file, ca-bundle.crt doesn't exist.

**Comment by abutcher** [comment]
lgtm

**Comment by dgoodwin** [comment]
Merged into overall 3.3 upgrade PR.

**Pull request merged**
